In [1]:
# Step1. NumPyをインポートするコードを記述する
import numpy as np


In [5]:
# Step2. AとBの行列を格納する多次元配列のコードを記述する
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [6]:
# Step3. 行列の積の計算をするコードを記述する
np.dot(A, B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [7]:
# Step4. Step3.の計算結果を表示するコードを記述する
T = np.dot(A, B)
print(T)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [8]:
#Step5. 行列の要素の最大値を求めるコードを記述する
T.max()

47